### PR TITLE
fix: make invited_by_id a mandatory field [#94]

### LINKED ISSUE #94: invited_by_id attribute in user table nil
### Steps to reproduce

Go into heroku console and return a user.

### What is the expected behavior?

That during sign up, the invitation code that is passed through the url params are used to determine who invited the user and their ID which is then set as an attribute.

### What is the actual behavior?

Attribute is always nil.

### What have you tried?

If I go through all the steps on localhost and look at the user instance the very last step before saving, the attribute is filled with a user ID. I don't know how to further test why it is then removed again on save.

### PR DESCRIPTION
**Pull request by papotte**
Issue number: resolves #94 

---------

### Description
Make `invited_by_id` a mandatory field. 
This required to change the order of updating the user object, with the first step is finding the inviting user and adding the ID to the user fields.

I added more tests to the general registration workflow and also some of the registration methods. Some refactoring was needed to write better tests!

### Checklist
- [x] Code compiles correctly
- [x] Created tests which fail without the change (if possible)
- [x] All tests passing
- [x] Rubocop passes

### CODE REVIEW

File: app/models/user.rb [hunk 1]
```diff
@@ -34,10 +34,11 @@ class User < ApplicationRecord # rubocop:disable Metrics/ClassLength
...
   validates_associated :characteristics, message: 'Let others know what is important to you', on: :create
-  validate  :validate_user_characteristics, on: :create
-  validate  :validate_age, on: :create
-  validate  :validate_travelling, on: :create
-  validate  :at_least_one_option_checked?, on: :create
+  validate :validate_user_characteristics, on: :create
+  validate :validate_age, on: :create
+  validate :validate_travelling, on: :create
+  validate :at_least_one_option_checked?, on: :create
+  validates :invited_by_id, on: :create, presence: { message: 'Please provide a valid invite code' }
```
Comment (lisbethpurrucker) [inline app/models/user.rb:41]: I think we can also remove these `on: :create`s. Not urgently right now, but I had to add those because of the user transfer from the old platform where we did not require any user attributes during the sign up. Therefore, whenever they came back to the new website and tried to reset their password which triggers a user update, they would not be able to. By now everyone should either have updated their password and logged in again or I can handle each case individually.

File: test/helpers/addresses.rb
Comment (lisbethpurrucker) [inline test/helpers/addresses.rb:1]: I am actually updating this addresses array on my current branch for the map as we need to have an address attribute which is a long string of all of the subattributes. And there is no street. Sorry, I should have spotted this right when you defined it. But we can leave it as is for this PR, I will fix it for the map PR.

**Review by lisbethpurrucker — APPROVED** [review]

File: app/models/user.rb (hunk 1 above)
Comment (papotte) [reply app/models/user.rb]: I'll do that in a separate PR, as this one is already complex enough and I don't know what consequences this change has :D

File: test/helpers/addresses.rb
Comment (papotte) [reply test/helpers/addresses.rb:1]: I'm taking this to slack cause it's a bigger thing, but I wouldn't make that change
